version: "3"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

services:
  go:
    container_name: ${COMPOSE_PROJECT_NAME}-go
    build:
      context: ../
      dockerfile: devenv/go/Dockerfile
    ports:
      - "${GO_EXPOSE_PORT}:80"
    volumes:
      - "../:/app"
    networks:
      - selfteam-components-net

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ./
      dockerfile: postgres/Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_NAME=${COMPOSE_PROJECT_NAME}
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./postgres/init.d/:/docker-entrypoint-initdb.d/"
    networks:
      - selfteam-components-net

networks:
  selfteam-components-net:
    name: selfteam-components-net
    driver: bridge
    ipam:
      driver: default